# Generated by Django 4.0.3 on 2023-03-07 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_automobile_automobilevo_customer_serviceappointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('customer_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=1000)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_rest.technician')),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='automobile',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='technician',
        ),
        migrations.RenameField(
            model_name='automobilevo',
            old_name='vin',
            new_name='import_vin',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
        migrations.DeleteModel(
            name='Automobile',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='ServiceAppointment',
        ),
    ]
